name = "blockless-net"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "blockless-net_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "blockless-net.wasm"
command = "npm run build:release"
